#!/bin/sh
#
# PROVIDE: @APPNAME@
# REQUIRE: NETWORKING SERVERS

# Example service file for a FreeBSD service
#  - Copy this file as /usr/local/etc/rc.d/@APPNAME@ and make it executable
#  - Then add '@APPNAME@_enable="YES"' to /etc/.rc.conf
#  - Then run '[sudo] service @APPNAME@ [start|stop|status]'
# See also https://docs.freebsd.org/en/books/handbook/config/#configtuning-starting-services

. /etc/rc.subr

name=@APPNAME@
desc="A simple chat server written in C"
rcvar=@APPNAME@_enable

start_cmd="app_start"
stop_cmd="app_stop"
status_cmd="app_status"

command="/usr/local/bin/${name}-server"

@APPNAME@_enable=${@APPNAME@_enable-"NO"}

pidfile=${@APPNAME@_pidfile-"/var/run/${name}.pid"}

app_start() {
    ${command} start
}

app_stop() {
    ${command} stop
}

app_status() {
    ${command} status
}

load_rc_config $name
run_rc_command "$1"

